### ISSUE TITLE
[BUG] - Testnet BP node connected to Testnet P2P Relay gets downgraded from hot to cold

### ISSUE THREAD

**Issue by johnnuy** [input-output-hk/cardano-node#3480]
External - Stake Pool - P2P

Hello, I'm noticing my block producer node using classic topology is losing connection to my relay node which is configured with P2P topology .  When I look in the logs, i'm finding the following:

[relay1:cardano.node.PeerSelectionActions:Info:12547] [2022-01-06 20:49:39.91 UTC] PeerStatusChanged (HotToCold (ConnectionId {localAddress = 10.184.1.203:3002, remoteAddress = 10.184.1.204:3001}))

looks like my testnet relay is occasionally downgrading my testnet block producer to cold status, which then causes the block producer to get disconnected

[core1:cardano.node.ErrorPolicy:Warning:586] [2022-01-06 20:49:39.91 UTC] IP 10.184.1.203:3002 ErrorPolicySuspendPeer (Just (ApplicationExceptionTrace (MuxError (MuxIOException Network.Socket.recvBuf: resource vanished (Connection reset by peer)) "(recv errored)")))

Need a way to keep my block producer as a hot node as far as my relay is concerned.

**Comment by os11k** [comment]
I agree with @johnnuy , maybe we can have BP in always hot mode.

**Comment by karknu** [comment]
A transition from hot to cold only happens due an error. There should be some log lines above the HotToCold message.

The most likely source of this would be that ChainSync timed out (look for `ExceededTimeLimit (ChainSync`), which will cause your node to tear down the connection and reconnect to your BP. This happens regardless of if you're running in p2p mode or not.

**Comment by os11k** [comment]
Interesting, so how happened that I have BP running for hours and connection is still not in hot mode. BP and relay in same network, so there are no issue with network for sure.

**Comment by os11k** [comment]
Just to add more details here. I experience this problem after I restarted BP. So it is logical while BP is restarted connection is demoted to cold one, but I would expect it become hot again and work properly, but this seems not a case here. Last time I restarted BP, connection become hot, I produced 1 block and then something happened and connection stacked in warm mode for hours and I missed 2 blocks.

On other hand, if I do restart of BP and then I restart relays after it, seems there are no such problem.

**Comment by johnnuy** [comment]
I will enable P2P again and see if I can get more information

**Comment by johnnuy** [comment]
Ok, so with the Relay (10.184.1.203) running P2P and core (10.184.1.204) node NOT running P2P I am getting a lot of this error in the logs:
[xxx:cardano.node.ConnectionManager:Info:4238] [2022-01-14 13:55:03.63 UTC] TrConnectionHandler (ConnectionId {localAddress = 10.184.1.203:3002, remoteAddress = 10.184.1.204:3001}) (TrError OutboundError ExceededTimeLimit (ChainSync (Header (HardForkBlock (': * ByronBlock (': * (ShelleyBlock (ShelleyEra StandardCrypto)) (': * (ShelleyBlock (ShelleyMAEra 'Allegra StandardCrypto)) (': * (ShelleyBlock (ShelleyMAEra 'Mary StandardCrypto)) (': * (ShelleyBlock (AlonzoEra StandardCrypto)) ('[] *)))))))) (Tip HardForkBlock (': * ByronBlock (': * (ShelleyBlock (ShelleyEra StandardCrypto)) (': * (ShelleyBlock (ShelleyMAEra 'Allegra StandardCrypto)) (': * (ShelleyBlock (ShelleyMAEra 'Mary StandardCrypto)) (': * (ShelleyBlock (AlonzoEra StandardCrypto)) ('[] *)))))))) (ServerAgency TokNext TokMustReply) ShutdownPeer)
[xxx:cardano.node.ConnectionManager:Info:4238] [2022-01-14 13:55:03.63 UTC] TrConnectionManagerCounters (ConnectionManagerCounters {fullDuplexConns = 3, duplexConns = 24, unidirectionalConns = 43, inboundConns = 22, outboundConns = 48})
[xxx:cardano.node.PeerSelectionActions:Info:4242] [2022-01-14 13:55:03.63 UTC] PeerStatusChanged (HotToCold (ConnectionId {localAddress = 10.184.1.203:3002, remoteAddress = 10.184.1.204:3001})),

I grepped all the logs for the past 5 days while not running P2P on my relay, and this does not show up at all for my local nodes. It shows up quite a bit of other node outside of my domain though.

Do I need to be running my core node also in P2P mode with only local connections?

**Comment by os11k** [comment]
Here is how I lost block tonight:

{"log":"\u001b[34m[optiplex:cardano.node.PeerSelectionActions:Info:22096]\u001b[0m [2022-01-15 01:15:17.53 UTC] PeerStatusChanged (HotToCold (ConnectionId {localAddress = 127.0.0.1:6002, remoteAddress = 127.0.0.1:6000}))\n","stream":"stdout","time":"2022-01-15T01:15:17.531152763Z"}
{"log":"\u001b[34m[optiplex:cardano.node.PeerSelectionActions:Info:26548]\u001b[0m [2022-01-15 01:15:27.46 UTC] PeerStatusChanged (ColdToWarm (Just 127.0.0.1:6002) 127.0.0.1:6000)\n","stream":"stdout","time":"2022-01-15T01:15:27.467205173Z"}
{"log":"\u001b[34m[optiplex:cardano.node.PeerSelectionActions:Info:26554]\u001b[0m [2022-01-15 01:15:27.46 UTC] PeerStatusChanged (WarmToHot (ConnectionId {localAddress = 127.0.0.1:6002, remoteAddress = 127.0.0.1:6000}))\n","stream":"stdout","time":"2022-01-15T01:15:27.468732145Z"}
{"log":"\u001b[34m[optiplex:cardano.node.PeerSelectionActions:Info:26552]\u001b[0m [2022-01-15 01:17:42.48 UTC] PeerStatusChanged (HotToCold (ConnectionId {localAddress = 127.0.0.1:6002, remoteAddress = 127.0.0.1:6000}))\n","stream":"stdout","time":"2022-01-15T01:17:42.484946355Z"}
{"log":"\u001b[34m[optiplex:cardano.node.PeerSelectionActions:Info:26892]\u001b[0m [2022-01-15 01:17:50.81 UTC] PeerStatusChanged (ColdToWarm (Just 127.0.0.1:6002) 127.0.0.1:6000)\n","stream":"stdout","time":"2022-01-15T01:17:50.811802695Z"}
{"log":"\u001b[34m[optiplex:cardano.node.PeerSelectionActions:Info:28747]\u001b[0m [2022-01-15 03:10:35.13 UTC] PeerStatusChanged (WarmToHot (ConnectionId {localAddress = 127.0.0.1:6002, remoteAddress = 127.0.0.1:6000}))\n","stream":"stdout","time":"2022-01-15T03:10:35.140730775Z"}

Slot assigned to me were 23325 at 2022-01-15T02:49:01+00:00

I see from BP logs that it was properly forged, but nobody fetched. Let me know if you need anymore data.

**Comment by os11k** [comment]
I just restarted both relays and one just stuck in Warm mode:

relay2:
[optiplex:cardano.node.PeerSelectionActions:Info:357] [2022-01-15 11:04:24.22 UTC] PeerStatusChanged (ColdToWarm (Just 127.0.0.1:6002) 127.0.0.1:6000)

relay1, has no this problem:
[optiplex:cardano.node.PeerSelectionActions:Info:374] [2022-01-15 10:40:22.52 UTC] PeerStatusChanged (ColdToWarm (Just 127.0.0.1:6001) 127.0.0.1:6000)
[optiplex:cardano.node.PeerSelectionActions:Info:459] [2022-01-15 10:40:22.53 UTC] PeerStatusChanged (WarmToHot (ConnectionId {localAddress = 127.0.0.1:6001, remoteAddress = 127.0.0.1:6000}))

**Comment by coot** [comment]
We believe this is fixed in the [p2p-master-1.33.0](https://github.com/input-output-hk/cardano-node/pull/3523) branch.  Please re-open if this is still a problem.

**Comment by os11k** [comment]
Does these fix is in 1.34.0-rc3? I'm still experiencing same issue with 1.34.0-rc3

**Comment by os11k** [comment]
```
[optiplex:cardano.node.PeerSelectionActions:Info:2377] [2022-02-26 08:45:04.55 UTC] PeerStatusChanged (HotToCold (ConnectionId {localAddress = 127.0.0.1:6002, remoteAddress = 127.0.0.1:6000}))
[optiplex:cardano.node.PeerSelectionActions:Info:12541] [2022-02-26 08:45:14.38 UTC] PeerStatusChanged (ColdToWarm (Just 127.0.0.1:6002) 127.0.0.1:6000)
[optiplex:cardano.node.PeerSelectionActions:Info:13176] [2022-02-26 09:37:00.39 UTC] PeerStatusChanged (WarmToHot (ConnectionId {localAddress = 127.0.0.1:6002, remoteAddress = 127.0.0.1:6000}))
```
As you can see BP what is peer 127.0.0.1:6000 were in cold mode for almost a hour today.

**Comment by coot** [comment]
@johnnuy @os11k we believe this is already fixed, though we'd appreciate if you join p2p testing group of friendly SPOs where we shared instructions how to run the p2p node (from which branch, etc).  Would you mind share with me your Discord handle so you can be invited?

**Comment by johnnuy** [comment]
@coot  Jonny [CAN1]#7583

**Comment by os11k** [comment]
I updated my nodes till 1.34 and I will monitor closely how it will perform. Will keep you posted

**Comment by johnnuy** [comment]
Literally within an hour of switching to 1.34.0 with P2P enabled I get the following
```
[2022-03-01 23:26:37.30 UTC] PeerStatusChanged (HotToCold (ConnectionId {localAddress = 10.184.1.203:3002, remoteAddress = 10.184.1.204:3001}))
 [2022-03-01 23:27:16.37 UTC] PeerStatusChanged (ColdToWarm (Just 10.184.1.203:3002) 10.184.1.204:3001)
 [2022-03-01 23:27:16.37 UTC] PeerStatusChanged (WarmToHot (ConnectionId {localAddress = 10.184.1.203:3002, remoteAddress = 10.184.1.204:3001}))
```

where 10.184.1.203 is my relay and 10.184.1.204 is my core, so yeah definitely not fixed.

**Comment by coot** [comment]
I don't think `1.34.0` contains all the patches.

**Comment by johnnuy** [comment]
> I don't think `1.34.0` contains all the patches.
Ok, is the p2p-master-1.33.0 branch the latest with all the patches?

**Comment by coot** [comment]
Yes

**Comment by coot** [comment]
And btw, just going cold is not an error, e.g. a timeout might fire because the other node was  too busy and didn't met its deadline; but the connection should be re-established shortly.

**Comment by coot** [comment]
@johnnuy you need to join our discord [server](https://discord.gg/WmSVtQ5PjZ).

**Comment by os11k** [comment]
Hi! Seems my issue was related to wrong configuration. I had Valency set to 1 in my topology file, but I had 2 accessPoints. Amount of accessPoints should be equal to what you put in Valency.

```
{
	"LocalRoots": {
		"groups": [
			{
				"localRoots": {
					"accessPoints": [
						{
							"address": "bp-host-name/ip",
							"port": 3001
						},
						{
							"address": "other-relay-hostname/ip",
							"port": 3001
						}
					],
					"advertise": false
				},
				"valency": 2
			}
		]
	},
	"PublicRoots": [
		{
			"publicRoots": {
				"accessPoints": [
					{
						"address": "relays-new.cardano-testnet.iohkdev.io",
						"port": 3001
					}
				],
				"advertise": true
			}
		}
	],
	"useLedgerAfterSlot": 0
}
```

In above config from relay1, we had accesspoints - 1 BP and 1 additional relay(relay2). To make it work it is needed to have Valency 2, I had 1 and seems because of that I had issues. Now with Valency 2 everything is stable.

**Comment by coot** [comment]
@os11k valency allows one to have redundancy without requiring more resources (upstream peers are costly); if you want to connect to all the specified relays / BPs then you're right it should be equal to the number of entries.
